import { ConvexError } from 'convex/values'

/**
 * Standardized error codes used across mutations and queries.
 * The client maps these to field-level errors or global toasts.
 */
export const ERROR_CODES = {
  // Auth / identity
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_EMAIL_CLAIM: 'MISSING_EMAIL_CLAIM',

  // Org state
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_INACTIVE: 'ORG_INACTIVE',
  CANNOT_MODIFY_INTERNAL_ORG: 'CANNOT_MODIFY_INTERNAL_ORG',

  // Slug validation
  SLUG_TAKEN: 'SLUG_TAKEN',
  SLUG_RESERVED: 'SLUG_RESERVED',
  SLUG_INVALID_FORMAT: 'SLUG_INVALID_FORMAT',

  // Invitations
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  USER_ALREADY_EXISTS_IN_ORG: 'USER_ALREADY_EXISTS_IN_ORG',
  CANNOT_INVITE_TO_INTERNAL_ORG: 'CANNOT_INVITE_TO_INTERNAL_ORG',
  CANNOT_INVITE_SUPER_ADMIN: 'CANNOT_INVITE_SUPER_ADMIN',

  // Conjuntos (F4)
  CONJUNTO_NOT_FOUND: 'CONJUNTO_NOT_FOUND',
  CONJUNTO_INACTIVE: 'CONJUNTO_INACTIVE',
  CONJUNTO_SLUG_TAKEN: 'CONJUNTO_SLUG_TAKEN',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_ALREADY_EXISTS: 'MEMBERSHIP_ALREADY_EXISTS',
  UNIDAD_DUPLICATE: 'UNIDAD_DUPLICATE',
  VEHICULO_PLACA_DUPLICATE: 'VEHICULO_PLACA_DUPLICATE',
  RESIDENTE_DOCUMENTO_DUPLICATE: 'RESIDENTE_DOCUMENTO_DUPLICATE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Registros de acceso (F5)
  REGISTRO_NOT_FOUND: 'REGISTRO_NOT_FOUND',
  REGISTRO_ALREADY_EXITED: 'REGISTRO_ALREADY_EXITED',
  VEHICULO_NOT_FOUND: 'VEHICULO_NOT_FOUND',
  UNIDAD_NOT_FOUND: 'UNIDAD_NOT_FOUND',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/**
 * Throws a ConvexError with a standardized code + message that the client
 * can match to show field-level errors or toasts.
 */
export function throwConvexError(code: ErrorCode, message: string): never {
  throw new ConvexError({ code, message })
}
