/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OrganizacionInactivaRouteImport } from './routes/organizacion-inactiva'
import { Route as NoRegistradoRouteImport } from './routes/no-registrado'
import { Route as NoAutorizadoRouteImport } from './routes/no-autorizado'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitacionRevocadaRouteImport } from './routes/invitacion-revocada'
import { Route as InvitacionExpiradaRouteImport } from './routes/invitacion-expirada'
import { Route as ErrorAuthRouteImport } from './routes/error-auth'
import { Route as CuentaDesactivadaRouteImport } from './routes/cuenta-desactivada'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSeleccionarConjuntoRouteImport } from './routes/_authenticated/seleccionar-conjunto'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedSuperAdminUsuariosRouteImport } from './routes/_authenticated/super-admin/usuarios'
import { Route as AuthenticatedSuperAdminConjuntosRouteImport } from './routes/_authenticated/super-admin/conjuntos'
import { Route as AuthenticatedAdminEquipoRouteImport } from './routes/_authenticated/admin/equipo'
import { Route as AuthenticatedCConjuntoIdRouteRouteImport } from './routes/_authenticated/c/$conjuntoId/route'
import { Route as AuthenticatedCConjuntoIdIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/index'
import { Route as AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport } from './routes/_authenticated/super-admin/organizaciones/$orgId'
import { Route as AuthenticatedCConjuntoIdUsuariosRouteImport } from './routes/_authenticated/c/$conjuntoId/usuarios'
import { Route as AuthenticatedCConjuntoIdConfiguracionRouteImport } from './routes/_authenticated/c/$conjuntoId/configuracion'
import { Route as AuthenticatedCConjuntoIdVehiculosIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/vehiculos/index'
import { Route as AuthenticatedCConjuntoIdUnidadesIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/unidades/index'
import { Route as AuthenticatedCConjuntoIdResidentesIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/residentes/index'
import { Route as AuthenticatedCConjuntoIdParqueaderosIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/parqueaderos/index'
import { Route as AuthenticatedCConjuntoIdControlAccesoIndexRouteImport } from './routes/_authenticated/c/$conjuntoId/control-acceso/index'
import { Route as AuthenticatedCConjuntoIdParqueaderosConfigurarRouteImport } from './routes/_authenticated/c/$conjuntoId/parqueaderos/configurar'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacionInactivaRoute = OrganizacionInactivaRouteImport.update({
  id: '/organizacion-inactiva',
  path: '/organizacion-inactiva',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRegistradoRoute = NoRegistradoRouteImport.update({
  id: '/no-registrado',
  path: '/no-registrado',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAutorizadoRoute = NoAutorizadoRouteImport.update({
  id: '/no-autorizado',
  path: '/no-autorizado',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRevocadaRoute = InvitacionRevocadaRouteImport.update({
  id: '/invitacion-revocada',
  path: '/invitacion-revocada',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionExpiradaRoute = InvitacionExpiradaRouteImport.update({
  id: '/invitacion-expirada',
  path: '/invitacion-expirada',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorAuthRoute = ErrorAuthRouteImport.update({
  id: '/error-auth',
  path: '/error-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaDesactivadaRoute = CuentaDesactivadaRouteImport.update({
  id: '/cuenta-desactivada',
  path: '/cuenta-desactivada',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeleccionarConjuntoRoute =
  AuthenticatedSeleccionarConjuntoRouteImport.update({
    id: '/seleccionar-conjunto',
    path: '/seleccionar-conjunto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminUsuariosRoute =
  AuthenticatedSuperAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminConjuntosRoute =
  AuthenticatedSuperAdminConjuntosRouteImport.update({
    id: '/conjuntos',
    path: '/conjuntos',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminEquipoRoute =
  AuthenticatedAdminEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdRouteRoute =
  AuthenticatedCConjuntoIdRouteRouteImport.update({
    id: '/c/$conjuntoId',
    path: '/c/$conjuntoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCConjuntoIdIndexRoute =
  AuthenticatedCConjuntoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedSuperAdminOrganizacionesOrgIdRoute =
  AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport.update({
    id: '/organizaciones/$orgId',
    path: '/organizaciones/$orgId',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdUsuariosRoute =
  AuthenticatedCConjuntoIdUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdConfiguracionRoute =
  AuthenticatedCConjuntoIdConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdVehiculosIndexRoute =
  AuthenticatedCConjuntoIdVehiculosIndexRouteImport.update({
    id: '/vehiculos/',
    path: '/vehiculos/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdUnidadesIndexRoute =
  AuthenticatedCConjuntoIdUnidadesIndexRouteImport.update({
    id: '/unidades/',
    path: '/unidades/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdResidentesIndexRoute =
  AuthenticatedCConjuntoIdResidentesIndexRouteImport.update({
    id: '/residentes/',
    path: '/residentes/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdParqueaderosIndexRoute =
  AuthenticatedCConjuntoIdParqueaderosIndexRouteImport.update({
    id: '/parqueaderos/',
    path: '/parqueaderos/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdControlAccesoIndexRoute =
  AuthenticatedCConjuntoIdControlAccesoIndexRouteImport.update({
    id: '/control-acceso/',
    path: '/control-acceso/',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)
const AuthenticatedCConjuntoIdParqueaderosConfigurarRoute =
  AuthenticatedCConjuntoIdParqueaderosConfigurarRouteImport.update({
    id: '/parqueaderos/configurar',
    path: '/parqueaderos/configurar',
    getParentRoute: () => AuthenticatedCConjuntoIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/c/$conjuntoId': typeof AuthenticatedCConjuntoIdRouteRouteWithChildren
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/c/$conjuntoId/configuracion': typeof AuthenticatedCConjuntoIdConfiguracionRoute
  '/c/$conjuntoId/usuarios': typeof AuthenticatedCConjuntoIdUsuariosRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/c/$conjuntoId/': typeof AuthenticatedCConjuntoIdIndexRoute
  '/c/$conjuntoId/parqueaderos/configurar': typeof AuthenticatedCConjuntoIdParqueaderosConfigurarRoute
  '/c/$conjuntoId/control-acceso/': typeof AuthenticatedCConjuntoIdControlAccesoIndexRoute
  '/c/$conjuntoId/parqueaderos/': typeof AuthenticatedCConjuntoIdParqueaderosIndexRoute
  '/c/$conjuntoId/residentes/': typeof AuthenticatedCConjuntoIdResidentesIndexRoute
  '/c/$conjuntoId/unidades/': typeof AuthenticatedCConjuntoIdUnidadesIndexRoute
  '/c/$conjuntoId/vehiculos/': typeof AuthenticatedCConjuntoIdVehiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/c/$conjuntoId/configuracion': typeof AuthenticatedCConjuntoIdConfiguracionRoute
  '/c/$conjuntoId/usuarios': typeof AuthenticatedCConjuntoIdUsuariosRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/c/$conjuntoId': typeof AuthenticatedCConjuntoIdIndexRoute
  '/c/$conjuntoId/parqueaderos/configurar': typeof AuthenticatedCConjuntoIdParqueaderosConfigurarRoute
  '/c/$conjuntoId/control-acceso': typeof AuthenticatedCConjuntoIdControlAccesoIndexRoute
  '/c/$conjuntoId/parqueaderos': typeof AuthenticatedCConjuntoIdParqueaderosIndexRoute
  '/c/$conjuntoId/residentes': typeof AuthenticatedCConjuntoIdResidentesIndexRoute
  '/c/$conjuntoId/unidades': typeof AuthenticatedCConjuntoIdUnidadesIndexRoute
  '/c/$conjuntoId/vehiculos': typeof AuthenticatedCConjuntoIdVehiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/_authenticated/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/_authenticated/c/$conjuntoId': typeof AuthenticatedCConjuntoIdRouteRouteWithChildren
  '/_authenticated/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/_authenticated/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/_authenticated/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/c/$conjuntoId/configuracion': typeof AuthenticatedCConjuntoIdConfiguracionRoute
  '/_authenticated/c/$conjuntoId/usuarios': typeof AuthenticatedCConjuntoIdUsuariosRoute
  '/_authenticated/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/_authenticated/c/$conjuntoId/': typeof AuthenticatedCConjuntoIdIndexRoute
  '/_authenticated/c/$conjuntoId/parqueaderos/configurar': typeof AuthenticatedCConjuntoIdParqueaderosConfigurarRoute
  '/_authenticated/c/$conjuntoId/control-acceso/': typeof AuthenticatedCConjuntoIdControlAccesoIndexRoute
  '/_authenticated/c/$conjuntoId/parqueaderos/': typeof AuthenticatedCConjuntoIdParqueaderosIndexRoute
  '/_authenticated/c/$conjuntoId/residentes/': typeof AuthenticatedCConjuntoIdResidentesIndexRoute
  '/_authenticated/c/$conjuntoId/unidades/': typeof AuthenticatedCConjuntoIdUnidadesIndexRoute
  '/_authenticated/c/$conjuntoId/vehiculos/': typeof AuthenticatedCConjuntoIdVehiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/admin'
    | '/super-admin'
    | '/seleccionar-conjunto'
    | '/c/$conjuntoId'
    | '/admin/equipo'
    | '/super-admin/conjuntos'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin/'
    | '/super-admin/'
    | '/c/$conjuntoId/configuracion'
    | '/c/$conjuntoId/usuarios'
    | '/super-admin/organizaciones/$orgId'
    | '/c/$conjuntoId/'
    | '/c/$conjuntoId/parqueaderos/configurar'
    | '/c/$conjuntoId/control-acceso/'
    | '/c/$conjuntoId/parqueaderos/'
    | '/c/$conjuntoId/residentes/'
    | '/c/$conjuntoId/unidades/'
    | '/c/$conjuntoId/vehiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/seleccionar-conjunto'
    | '/admin/equipo'
    | '/super-admin/conjuntos'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin'
    | '/super-admin'
    | '/c/$conjuntoId/configuracion'
    | '/c/$conjuntoId/usuarios'
    | '/super-admin/organizaciones/$orgId'
    | '/c/$conjuntoId'
    | '/c/$conjuntoId/parqueaderos/configurar'
    | '/c/$conjuntoId/control-acceso'
    | '/c/$conjuntoId/parqueaderos'
    | '/c/$conjuntoId/residentes'
    | '/c/$conjuntoId/unidades'
    | '/c/$conjuntoId/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/_authenticated/admin'
    | '/_authenticated/super-admin'
    | '/_authenticated/seleccionar-conjunto'
    | '/_authenticated/c/$conjuntoId'
    | '/_authenticated/admin/equipo'
    | '/_authenticated/super-admin/conjuntos'
    | '/_authenticated/super-admin/usuarios'
    | '/api/auth/callback'
    | '/_authenticated/admin/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/c/$conjuntoId/configuracion'
    | '/_authenticated/c/$conjuntoId/usuarios'
    | '/_authenticated/super-admin/organizaciones/$orgId'
    | '/_authenticated/c/$conjuntoId/'
    | '/_authenticated/c/$conjuntoId/parqueaderos/configurar'
    | '/_authenticated/c/$conjuntoId/control-acceso/'
    | '/_authenticated/c/$conjuntoId/parqueaderos/'
    | '/_authenticated/c/$conjuntoId/residentes/'
    | '/_authenticated/c/$conjuntoId/unidades/'
    | '/_authenticated/c/$conjuntoId/vehiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CuentaDesactivadaRoute: typeof CuentaDesactivadaRoute
  ErrorAuthRoute: typeof ErrorAuthRoute
  InvitacionExpiradaRoute: typeof InvitacionExpiradaRoute
  InvitacionRevocadaRoute: typeof InvitacionRevocadaRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NoAutorizadoRoute: typeof NoAutorizadoRoute
  NoRegistradoRoute: typeof NoRegistradoRoute
  OrganizacionInactivaRoute: typeof OrganizacionInactivaRoute
  ProgressRoute: typeof ProgressRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacion-inactiva': {
      id: '/organizacion-inactiva'
      path: '/organizacion-inactiva'
      fullPath: '/organizacion-inactiva'
      preLoaderRoute: typeof OrganizacionInactivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-registrado': {
      id: '/no-registrado'
      path: '/no-registrado'
      fullPath: '/no-registrado'
      preLoaderRoute: typeof NoRegistradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-autorizado': {
      id: '/no-autorizado'
      path: '/no-autorizado'
      fullPath: '/no-autorizado'
      preLoaderRoute: typeof NoAutorizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-revocada': {
      id: '/invitacion-revocada'
      path: '/invitacion-revocada'
      fullPath: '/invitacion-revocada'
      preLoaderRoute: typeof InvitacionRevocadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-expirada': {
      id: '/invitacion-expirada'
      path: '/invitacion-expirada'
      fullPath: '/invitacion-expirada'
      preLoaderRoute: typeof InvitacionExpiradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-auth': {
      id: '/error-auth'
      path: '/error-auth'
      fullPath: '/error-auth'
      preLoaderRoute: typeof ErrorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta-desactivada': {
      id: '/cuenta-desactivada'
      path: '/cuenta-desactivada'
      fullPath: '/cuenta-desactivada'
      preLoaderRoute: typeof CuentaDesactivadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seleccionar-conjunto': {
      id: '/_authenticated/seleccionar-conjunto'
      path: '/seleccionar-conjunto'
      fullPath: '/seleccionar-conjunto'
      preLoaderRoute: typeof AuthenticatedSeleccionarConjuntoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/usuarios': {
      id: '/_authenticated/super-admin/usuarios'
      path: '/usuarios'
      fullPath: '/super-admin/usuarios'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/conjuntos': {
      id: '/_authenticated/super-admin/conjuntos'
      path: '/conjuntos'
      fullPath: '/super-admin/conjuntos'
      preLoaderRoute: typeof AuthenticatedSuperAdminConjuntosRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/equipo': {
      id: '/_authenticated/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AuthenticatedAdminEquipoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/c/$conjuntoId': {
      id: '/_authenticated/c/$conjuntoId'
      path: '/c/$conjuntoId'
      fullPath: '/c/$conjuntoId'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$conjuntoId/': {
      id: '/_authenticated/c/$conjuntoId/'
      path: '/'
      fullPath: '/c/$conjuntoId/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/super-admin/organizaciones/$orgId': {
      id: '/_authenticated/super-admin/organizaciones/$orgId'
      path: '/organizaciones/$orgId'
      fullPath: '/super-admin/organizaciones/$orgId'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/c/$conjuntoId/usuarios': {
      id: '/_authenticated/c/$conjuntoId/usuarios'
      path: '/usuarios'
      fullPath: '/c/$conjuntoId/usuarios'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdUsuariosRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/configuracion': {
      id: '/_authenticated/c/$conjuntoId/configuracion'
      path: '/configuracion'
      fullPath: '/c/$conjuntoId/configuracion'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdConfiguracionRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/vehiculos/': {
      id: '/_authenticated/c/$conjuntoId/vehiculos/'
      path: '/vehiculos'
      fullPath: '/c/$conjuntoId/vehiculos/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdVehiculosIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/unidades/': {
      id: '/_authenticated/c/$conjuntoId/unidades/'
      path: '/unidades'
      fullPath: '/c/$conjuntoId/unidades/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdUnidadesIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/residentes/': {
      id: '/_authenticated/c/$conjuntoId/residentes/'
      path: '/residentes'
      fullPath: '/c/$conjuntoId/residentes/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdResidentesIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/parqueaderos/': {
      id: '/_authenticated/c/$conjuntoId/parqueaderos/'
      path: '/parqueaderos'
      fullPath: '/c/$conjuntoId/parqueaderos/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdParqueaderosIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/control-acceso/': {
      id: '/_authenticated/c/$conjuntoId/control-acceso/'
      path: '/control-acceso'
      fullPath: '/c/$conjuntoId/control-acceso/'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdControlAccesoIndexRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
    '/_authenticated/c/$conjuntoId/parqueaderos/configurar': {
      id: '/_authenticated/c/$conjuntoId/parqueaderos/configurar'
      path: '/parqueaderos/configurar'
      fullPath: '/c/$conjuntoId/parqueaderos/configurar'
      preLoaderRoute: typeof AuthenticatedCConjuntoIdParqueaderosConfigurarRouteImport
      parentRoute: typeof AuthenticatedCConjuntoIdRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminEquipoRoute: typeof AuthenticatedAdminEquipoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminEquipoRoute: AuthenticatedAdminEquipoRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminConjuntosRoute: typeof AuthenticatedSuperAdminConjuntosRoute
  AuthenticatedSuperAdminUsuariosRoute: typeof AuthenticatedSuperAdminUsuariosRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminOrganizacionesOrgIdRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminConjuntosRoute:
      AuthenticatedSuperAdminConjuntosRoute,
    AuthenticatedSuperAdminUsuariosRoute: AuthenticatedSuperAdminUsuariosRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminOrganizacionesOrgIdRoute:
      AuthenticatedSuperAdminOrganizacionesOrgIdRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedCConjuntoIdRouteRouteChildren {
  AuthenticatedCConjuntoIdConfiguracionRoute: typeof AuthenticatedCConjuntoIdConfiguracionRoute
  AuthenticatedCConjuntoIdUsuariosRoute: typeof AuthenticatedCConjuntoIdUsuariosRoute
  AuthenticatedCConjuntoIdIndexRoute: typeof AuthenticatedCConjuntoIdIndexRoute
  AuthenticatedCConjuntoIdParqueaderosConfigurarRoute: typeof AuthenticatedCConjuntoIdParqueaderosConfigurarRoute
  AuthenticatedCConjuntoIdControlAccesoIndexRoute: typeof AuthenticatedCConjuntoIdControlAccesoIndexRoute
  AuthenticatedCConjuntoIdParqueaderosIndexRoute: typeof AuthenticatedCConjuntoIdParqueaderosIndexRoute
  AuthenticatedCConjuntoIdResidentesIndexRoute: typeof AuthenticatedCConjuntoIdResidentesIndexRoute
  AuthenticatedCConjuntoIdUnidadesIndexRoute: typeof AuthenticatedCConjuntoIdUnidadesIndexRoute
  AuthenticatedCConjuntoIdVehiculosIndexRoute: typeof AuthenticatedCConjuntoIdVehiculosIndexRoute
}

const AuthenticatedCConjuntoIdRouteRouteChildren: AuthenticatedCConjuntoIdRouteRouteChildren =
  {
    AuthenticatedCConjuntoIdConfiguracionRoute:
      AuthenticatedCConjuntoIdConfiguracionRoute,
    AuthenticatedCConjuntoIdUsuariosRoute:
      AuthenticatedCConjuntoIdUsuariosRoute,
    AuthenticatedCConjuntoIdIndexRoute: AuthenticatedCConjuntoIdIndexRoute,
    AuthenticatedCConjuntoIdParqueaderosConfigurarRoute:
      AuthenticatedCConjuntoIdParqueaderosConfigurarRoute,
    AuthenticatedCConjuntoIdControlAccesoIndexRoute:
      AuthenticatedCConjuntoIdControlAccesoIndexRoute,
    AuthenticatedCConjuntoIdParqueaderosIndexRoute:
      AuthenticatedCConjuntoIdParqueaderosIndexRoute,
    AuthenticatedCConjuntoIdResidentesIndexRoute:
      AuthenticatedCConjuntoIdResidentesIndexRoute,
    AuthenticatedCConjuntoIdUnidadesIndexRoute:
      AuthenticatedCConjuntoIdUnidadesIndexRoute,
    AuthenticatedCConjuntoIdVehiculosIndexRoute:
      AuthenticatedCConjuntoIdVehiculosIndexRoute,
  }

const AuthenticatedCConjuntoIdRouteRouteWithChildren =
  AuthenticatedCConjuntoIdRouteRoute._addFileChildren(
    AuthenticatedCConjuntoIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedSeleccionarConjuntoRoute: typeof AuthenticatedSeleccionarConjuntoRoute
  AuthenticatedCConjuntoIdRouteRoute: typeof AuthenticatedCConjuntoIdRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedSeleccionarConjuntoRoute: AuthenticatedSeleccionarConjuntoRoute,
  AuthenticatedCConjuntoIdRouteRoute:
    AuthenticatedCConjuntoIdRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CuentaDesactivadaRoute: CuentaDesactivadaRoute,
  ErrorAuthRoute: ErrorAuthRoute,
  InvitacionExpiradaRoute: InvitacionExpiradaRoute,
  InvitacionRevocadaRoute: InvitacionRevocadaRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NoAutorizadoRoute: NoAutorizadoRoute,
  NoRegistradoRoute: NoRegistradoRoute,
  OrganizacionInactivaRoute: OrganizacionInactivaRoute,
  ProgressRoute: ProgressRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
