/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { getRouter } from './router.tsx'
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport } from './routes/_authenticated/super-admin/organizaciones/$orgId'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as AuthenticatedSuperAdminUsuariosRouteImport } from './routes/_authenticated/super-admin/usuarios'
import { Route as AuthenticatedVigilanteIndexRouteImport } from './routes/_authenticated/vigilante/index'
import { Route as AuthenticatedVigilanteRouteRouteImport } from './routes/_authenticated/vigilante/route'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as CuentaDesactivadaRouteImport } from './routes/cuenta-desactivada'
import { Route as ErrorAuthRouteImport } from './routes/error-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionExpiradaRouteImport } from './routes/invitacion-expirada'
import { Route as InvitacionRevocadaRouteImport } from './routes/invitacion-revocada'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as NoAutorizadoRouteImport } from './routes/no-autorizado'
import { Route as NoRegistradoRouteImport } from './routes/no-registrado'
import { Route as OrganizacionInactivaRouteImport } from './routes/organizacion-inactiva'
import { Route as ProgressRouteImport } from './routes/progress'
import type { startInstance } from './start.ts'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacionInactivaRoute = OrganizacionInactivaRouteImport.update({
  id: '/organizacion-inactiva',
  path: '/organizacion-inactiva',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRegistradoRoute = NoRegistradoRouteImport.update({
  id: '/no-registrado',
  path: '/no-registrado',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAutorizadoRoute = NoAutorizadoRouteImport.update({
  id: '/no-autorizado',
  path: '/no-autorizado',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRevocadaRoute = InvitacionRevocadaRouteImport.update({
  id: '/invitacion-revocada',
  path: '/invitacion-revocada',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionExpiradaRoute = InvitacionExpiradaRouteImport.update({
  id: '/invitacion-expirada',
  path: '/invitacion-expirada',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorAuthRoute = ErrorAuthRouteImport.update({
  id: '/error-auth',
  path: '/error-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaDesactivadaRoute = CuentaDesactivadaRouteImport.update({
  id: '/cuenta-desactivada',
  path: '/cuenta-desactivada',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVigilanteRouteRoute =
  AuthenticatedVigilanteRouteRouteImport.update({
    id: '/vigilante',
    path: '/vigilante',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVigilanteIndexRoute =
  AuthenticatedVigilanteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVigilanteRouteRoute,
  } as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminUsuariosRoute =
  AuthenticatedSuperAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminOrganizacionesOrgIdRoute =
  AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport.update({
    id: '/organizaciones/$orgId',
    path: '/organizaciones/$orgId',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/vigilante': typeof AuthenticatedVigilanteRouteRouteWithChildren
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/vigilante/': typeof AuthenticatedVigilanteIndexRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/vigilante': typeof AuthenticatedVigilanteIndexRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/_authenticated/vigilante': typeof AuthenticatedVigilanteRouteRouteWithChildren
  '/_authenticated/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/vigilante/': typeof AuthenticatedVigilanteIndexRoute
  '/_authenticated/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/admin'
    | '/super-admin'
    | '/vigilante'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin/'
    | '/super-admin/'
    | '/vigilante/'
    | '/super-admin/organizaciones/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin'
    | '/super-admin'
    | '/vigilante'
    | '/super-admin/organizaciones/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/_authenticated/admin'
    | '/_authenticated/super-admin'
    | '/_authenticated/vigilante'
    | '/_authenticated/super-admin/usuarios'
    | '/api/auth/callback'
    | '/_authenticated/admin/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/vigilante/'
    | '/_authenticated/super-admin/organizaciones/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CuentaDesactivadaRoute: typeof CuentaDesactivadaRoute
  ErrorAuthRoute: typeof ErrorAuthRoute
  InvitacionExpiradaRoute: typeof InvitacionExpiradaRoute
  InvitacionRevocadaRoute: typeof InvitacionRevocadaRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NoAutorizadoRoute: typeof NoAutorizadoRoute
  NoRegistradoRoute: typeof NoRegistradoRoute
  OrganizacionInactivaRoute: typeof OrganizacionInactivaRoute
  ProgressRoute: typeof ProgressRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacion-inactiva': {
      id: '/organizacion-inactiva'
      path: '/organizacion-inactiva'
      fullPath: '/organizacion-inactiva'
      preLoaderRoute: typeof OrganizacionInactivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-registrado': {
      id: '/no-registrado'
      path: '/no-registrado'
      fullPath: '/no-registrado'
      preLoaderRoute: typeof NoRegistradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-autorizado': {
      id: '/no-autorizado'
      path: '/no-autorizado'
      fullPath: '/no-autorizado'
      preLoaderRoute: typeof NoAutorizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-revocada': {
      id: '/invitacion-revocada'
      path: '/invitacion-revocada'
      fullPath: '/invitacion-revocada'
      preLoaderRoute: typeof InvitacionRevocadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-expirada': {
      id: '/invitacion-expirada'
      path: '/invitacion-expirada'
      fullPath: '/invitacion-expirada'
      preLoaderRoute: typeof InvitacionExpiradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-auth': {
      id: '/error-auth'
      path: '/error-auth'
      fullPath: '/error-auth'
      preLoaderRoute: typeof ErrorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta-desactivada': {
      id: '/cuenta-desactivada'
      path: '/cuenta-desactivada'
      fullPath: '/cuenta-desactivada'
      preLoaderRoute: typeof CuentaDesactivadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vigilante': {
      id: '/_authenticated/vigilante'
      path: '/vigilante'
      fullPath: '/vigilante'
      preLoaderRoute: typeof AuthenticatedVigilanteRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vigilante/': {
      id: '/_authenticated/vigilante/'
      path: '/'
      fullPath: '/vigilante/'
      preLoaderRoute: typeof AuthenticatedVigilanteIndexRouteImport
      parentRoute: typeof AuthenticatedVigilanteRouteRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/usuarios': {
      id: '/_authenticated/super-admin/usuarios'
      path: '/usuarios'
      fullPath: '/super-admin/usuarios'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/organizaciones/$orgId': {
      id: '/_authenticated/super-admin/organizaciones/$orgId'
      path: '/organizaciones/$orgId'
      fullPath: '/super-admin/organizaciones/$orgId'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminUsuariosRoute: typeof AuthenticatedSuperAdminUsuariosRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminOrganizacionesOrgIdRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminUsuariosRoute: AuthenticatedSuperAdminUsuariosRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminOrganizacionesOrgIdRoute:
      AuthenticatedSuperAdminOrganizacionesOrgIdRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedVigilanteRouteRouteChildren {
  AuthenticatedVigilanteIndexRoute: typeof AuthenticatedVigilanteIndexRoute
}

const AuthenticatedVigilanteRouteRouteChildren: AuthenticatedVigilanteRouteRouteChildren =
  {
    AuthenticatedVigilanteIndexRoute: AuthenticatedVigilanteIndexRoute,
  }

const AuthenticatedVigilanteRouteRouteWithChildren =
  AuthenticatedVigilanteRouteRoute._addFileChildren(
    AuthenticatedVigilanteRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedVigilanteRouteRoute: typeof AuthenticatedVigilanteRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedVigilanteRouteRoute:
    AuthenticatedVigilanteRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CuentaDesactivadaRoute: CuentaDesactivadaRoute,
  ErrorAuthRoute: ErrorAuthRoute,
  InvitacionExpiradaRoute: InvitacionExpiradaRoute,
  InvitacionRevocadaRoute: InvitacionRevocadaRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NoAutorizadoRoute: NoAutorizadoRoute,
  NoRegistradoRoute: NoRegistradoRoute,
  OrganizacionInactivaRoute: OrganizacionInactivaRoute,
  ProgressRoute: ProgressRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
