/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { getRouter } from './router.tsx'
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminEquipoRouteImport } from './routes/_authenticated/admin/equipo'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCComplexSlugCommunicationsIndexRouteImport } from './routes/_authenticated/c/$complexSlug/communications/index'
import { Route as AuthenticatedCComplexSlugConfiguracionRouteImport } from './routes/_authenticated/c/$complexSlug/configuracion'
import { Route as AuthenticatedCComplexSlugControlAccesoIndexRouteImport } from './routes/_authenticated/c/$complexSlug/control-acceso/index'
import { Route as AuthenticatedCComplexSlugIndexRouteImport } from './routes/_authenticated/c/$complexSlug/index'
import { Route as AuthenticatedCComplexSlugResidentesIndexRouteImport } from './routes/_authenticated/c/$complexSlug/residentes/index'
import { Route as AuthenticatedCComplexSlugRouteRouteImport } from './routes/_authenticated/c/$complexSlug/route'
import { Route as AuthenticatedCComplexSlugUnidadesIndexRouteImport } from './routes/_authenticated/c/$complexSlug/unidades/index'
import { Route as AuthenticatedCComplexSlugUsuariosRouteImport } from './routes/_authenticated/c/$complexSlug/usuarios'
import { Route as AuthenticatedCComplexSlugVehiculosIndexRouteImport } from './routes/_authenticated/c/$complexSlug/vehiculos/index'
import { Route as AuthenticatedSeleccionarConjuntoRouteImport } from './routes/_authenticated/seleccionar-conjunto'
import { Route as AuthenticatedSuperAdminConjuntosRouteImport } from './routes/_authenticated/super-admin/conjuntos'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport } from './routes/_authenticated/super-admin/organizaciones/$orgId'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as AuthenticatedSuperAdminUsuariosRouteImport } from './routes/_authenticated/super-admin/usuarios'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as CuentaDesactivadaRouteImport } from './routes/cuenta-desactivada'
import { Route as ErrorAuthRouteImport } from './routes/error-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionExpiradaRouteImport } from './routes/invitacion-expirada'
import { Route as InvitacionRevocadaRouteImport } from './routes/invitacion-revocada'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as NoAutorizadoRouteImport } from './routes/no-autorizado'
import { Route as NoRegistradoRouteImport } from './routes/no-registrado'
import { Route as OrganizacionInactivaRouteImport } from './routes/organizacion-inactiva'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TunnelRouteImport } from './routes/tunnel'
import type { startInstance } from './start.ts'

const TunnelRoute = TunnelRouteImport.update({
  id: '/tunnel',
  path: '/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacionInactivaRoute = OrganizacionInactivaRouteImport.update({
  id: '/organizacion-inactiva',
  path: '/organizacion-inactiva',
  getParentRoute: () => rootRouteImport,
} as any)
const NoRegistradoRoute = NoRegistradoRouteImport.update({
  id: '/no-registrado',
  path: '/no-registrado',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAutorizadoRoute = NoAutorizadoRouteImport.update({
  id: '/no-autorizado',
  path: '/no-autorizado',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionRevocadaRoute = InvitacionRevocadaRouteImport.update({
  id: '/invitacion-revocada',
  path: '/invitacion-revocada',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionExpiradaRoute = InvitacionExpiradaRouteImport.update({
  id: '/invitacion-expirada',
  path: '/invitacion-expirada',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorAuthRoute = ErrorAuthRouteImport.update({
  id: '/error-auth',
  path: '/error-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaDesactivadaRoute = CuentaDesactivadaRouteImport.update({
  id: '/cuenta-desactivada',
  path: '/cuenta-desactivada',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSeleccionarConjuntoRoute =
  AuthenticatedSeleccionarConjuntoRouteImport.update({
    id: '/seleccionar-conjunto',
    path: '/seleccionar-conjunto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminUsuariosRoute =
  AuthenticatedSuperAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminConjuntosRoute =
  AuthenticatedSuperAdminConjuntosRouteImport.update({
    id: '/conjuntos',
    path: '/conjuntos',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminEquipoRoute =
  AuthenticatedAdminEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCComplexSlugRouteRoute =
  AuthenticatedCComplexSlugRouteRouteImport.update({
    id: '/c/$complexSlug',
    path: '/c/$complexSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCComplexSlugIndexRoute =
  AuthenticatedCComplexSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedSuperAdminOrganizacionesOrgIdRoute =
  AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport.update({
    id: '/organizaciones/$orgId',
    path: '/organizaciones/$orgId',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedCComplexSlugUsuariosRoute =
  AuthenticatedCComplexSlugUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugConfiguracionRoute =
  AuthenticatedCComplexSlugConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugVehiculosIndexRoute =
  AuthenticatedCComplexSlugVehiculosIndexRouteImport.update({
    id: '/vehiculos/',
    path: '/vehiculos/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugUnidadesIndexRoute =
  AuthenticatedCComplexSlugUnidadesIndexRouteImport.update({
    id: '/unidades/',
    path: '/unidades/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugResidentesIndexRoute =
  AuthenticatedCComplexSlugResidentesIndexRouteImport.update({
    id: '/residentes/',
    path: '/residentes/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugControlAccesoIndexRoute =
  AuthenticatedCComplexSlugControlAccesoIndexRouteImport.update({
    id: '/control-acceso/',
    path: '/control-acceso/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)
const AuthenticatedCComplexSlugCommunicationsIndexRoute =
  AuthenticatedCComplexSlugCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => AuthenticatedCComplexSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/tunnel': typeof TunnelRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/c/$complexSlug': typeof AuthenticatedCComplexSlugRouteRouteWithChildren
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/c/$complexSlug/configuracion': typeof AuthenticatedCComplexSlugConfiguracionRoute
  '/c/$complexSlug/usuarios': typeof AuthenticatedCComplexSlugUsuariosRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/c/$complexSlug/': typeof AuthenticatedCComplexSlugIndexRoute
  '/c/$complexSlug/communications/': typeof AuthenticatedCComplexSlugCommunicationsIndexRoute
  '/c/$complexSlug/control-acceso/': typeof AuthenticatedCComplexSlugControlAccesoIndexRoute
  '/c/$complexSlug/residentes/': typeof AuthenticatedCComplexSlugResidentesIndexRoute
  '/c/$complexSlug/unidades/': typeof AuthenticatedCComplexSlugUnidadesIndexRoute
  '/c/$complexSlug/vehiculos/': typeof AuthenticatedCComplexSlugVehiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/tunnel': typeof TunnelRoute
  '/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/c/$complexSlug/configuracion': typeof AuthenticatedCComplexSlugConfiguracionRoute
  '/c/$complexSlug/usuarios': typeof AuthenticatedCComplexSlugUsuariosRoute
  '/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/c/$complexSlug': typeof AuthenticatedCComplexSlugIndexRoute
  '/c/$complexSlug/communications': typeof AuthenticatedCComplexSlugCommunicationsIndexRoute
  '/c/$complexSlug/control-acceso': typeof AuthenticatedCComplexSlugControlAccesoIndexRoute
  '/c/$complexSlug/residentes': typeof AuthenticatedCComplexSlugResidentesIndexRoute
  '/c/$complexSlug/unidades': typeof AuthenticatedCComplexSlugUnidadesIndexRoute
  '/c/$complexSlug/vehiculos': typeof AuthenticatedCComplexSlugVehiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cuenta-desactivada': typeof CuentaDesactivadaRoute
  '/error-auth': typeof ErrorAuthRoute
  '/invitacion-expirada': typeof InvitacionExpiradaRoute
  '/invitacion-revocada': typeof InvitacionRevocadaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/no-autorizado': typeof NoAutorizadoRoute
  '/no-registrado': typeof NoRegistradoRoute
  '/organizacion-inactiva': typeof OrganizacionInactivaRoute
  '/progress': typeof ProgressRoute
  '/tunnel': typeof TunnelRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/_authenticated/seleccionar-conjunto': typeof AuthenticatedSeleccionarConjuntoRoute
  '/_authenticated/c/$complexSlug': typeof AuthenticatedCComplexSlugRouteRouteWithChildren
  '/_authenticated/admin/equipo': typeof AuthenticatedAdminEquipoRoute
  '/_authenticated/super-admin/conjuntos': typeof AuthenticatedSuperAdminConjuntosRoute
  '/_authenticated/super-admin/usuarios': typeof AuthenticatedSuperAdminUsuariosRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/c/$complexSlug/configuracion': typeof AuthenticatedCComplexSlugConfiguracionRoute
  '/_authenticated/c/$complexSlug/usuarios': typeof AuthenticatedCComplexSlugUsuariosRoute
  '/_authenticated/super-admin/organizaciones/$orgId': typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
  '/_authenticated/c/$complexSlug/': typeof AuthenticatedCComplexSlugIndexRoute
  '/_authenticated/c/$complexSlug/communications/': typeof AuthenticatedCComplexSlugCommunicationsIndexRoute
  '/_authenticated/c/$complexSlug/control-acceso/': typeof AuthenticatedCComplexSlugControlAccesoIndexRoute
  '/_authenticated/c/$complexSlug/residentes/': typeof AuthenticatedCComplexSlugResidentesIndexRoute
  '/_authenticated/c/$complexSlug/unidades/': typeof AuthenticatedCComplexSlugUnidadesIndexRoute
  '/_authenticated/c/$complexSlug/vehiculos/': typeof AuthenticatedCComplexSlugVehiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/tunnel'
    | '/admin'
    | '/super-admin'
    | '/seleccionar-conjunto'
    | '/c/$complexSlug'
    | '/admin/equipo'
    | '/super-admin/conjuntos'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin/'
    | '/super-admin/'
    | '/c/$complexSlug/configuracion'
    | '/c/$complexSlug/usuarios'
    | '/super-admin/organizaciones/$orgId'
    | '/c/$complexSlug/'
    | '/c/$complexSlug/communications/'
    | '/c/$complexSlug/control-acceso/'
    | '/c/$complexSlug/residentes/'
    | '/c/$complexSlug/unidades/'
    | '/c/$complexSlug/vehiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/tunnel'
    | '/seleccionar-conjunto'
    | '/admin/equipo'
    | '/super-admin/conjuntos'
    | '/super-admin/usuarios'
    | '/api/auth/callback'
    | '/admin'
    | '/super-admin'
    | '/c/$complexSlug/configuracion'
    | '/c/$complexSlug/usuarios'
    | '/super-admin/organizaciones/$orgId'
    | '/c/$complexSlug'
    | '/c/$complexSlug/communications'
    | '/c/$complexSlug/control-acceso'
    | '/c/$complexSlug/residentes'
    | '/c/$complexSlug/unidades'
    | '/c/$complexSlug/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cuenta-desactivada'
    | '/error-auth'
    | '/invitacion-expirada'
    | '/invitacion-revocada'
    | '/login'
    | '/logout'
    | '/no-autorizado'
    | '/no-registrado'
    | '/organizacion-inactiva'
    | '/progress'
    | '/tunnel'
    | '/_authenticated/admin'
    | '/_authenticated/super-admin'
    | '/_authenticated/seleccionar-conjunto'
    | '/_authenticated/c/$complexSlug'
    | '/_authenticated/admin/equipo'
    | '/_authenticated/super-admin/conjuntos'
    | '/_authenticated/super-admin/usuarios'
    | '/api/auth/callback'
    | '/_authenticated/admin/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/c/$complexSlug/configuracion'
    | '/_authenticated/c/$complexSlug/usuarios'
    | '/_authenticated/super-admin/organizaciones/$orgId'
    | '/_authenticated/c/$complexSlug/'
    | '/_authenticated/c/$complexSlug/communications/'
    | '/_authenticated/c/$complexSlug/control-acceso/'
    | '/_authenticated/c/$complexSlug/residentes/'
    | '/_authenticated/c/$complexSlug/unidades/'
    | '/_authenticated/c/$complexSlug/vehiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CuentaDesactivadaRoute: typeof CuentaDesactivadaRoute
  ErrorAuthRoute: typeof ErrorAuthRoute
  InvitacionExpiradaRoute: typeof InvitacionExpiradaRoute
  InvitacionRevocadaRoute: typeof InvitacionRevocadaRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  NoAutorizadoRoute: typeof NoAutorizadoRoute
  NoRegistradoRoute: typeof NoRegistradoRoute
  OrganizacionInactivaRoute: typeof OrganizacionInactivaRoute
  ProgressRoute: typeof ProgressRoute
  TunnelRoute: typeof TunnelRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tunnel': {
      id: '/tunnel'
      path: '/tunnel'
      fullPath: '/tunnel'
      preLoaderRoute: typeof TunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacion-inactiva': {
      id: '/organizacion-inactiva'
      path: '/organizacion-inactiva'
      fullPath: '/organizacion-inactiva'
      preLoaderRoute: typeof OrganizacionInactivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-registrado': {
      id: '/no-registrado'
      path: '/no-registrado'
      fullPath: '/no-registrado'
      preLoaderRoute: typeof NoRegistradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-autorizado': {
      id: '/no-autorizado'
      path: '/no-autorizado'
      fullPath: '/no-autorizado'
      preLoaderRoute: typeof NoAutorizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-revocada': {
      id: '/invitacion-revocada'
      path: '/invitacion-revocada'
      fullPath: '/invitacion-revocada'
      preLoaderRoute: typeof InvitacionRevocadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion-expirada': {
      id: '/invitacion-expirada'
      path: '/invitacion-expirada'
      fullPath: '/invitacion-expirada'
      preLoaderRoute: typeof InvitacionExpiradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-auth': {
      id: '/error-auth'
      path: '/error-auth'
      fullPath: '/error-auth'
      preLoaderRoute: typeof ErrorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta-desactivada': {
      id: '/cuenta-desactivada'
      path: '/cuenta-desactivada'
      fullPath: '/cuenta-desactivada'
      preLoaderRoute: typeof CuentaDesactivadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seleccionar-conjunto': {
      id: '/_authenticated/seleccionar-conjunto'
      path: '/seleccionar-conjunto'
      fullPath: '/seleccionar-conjunto'
      preLoaderRoute: typeof AuthenticatedSeleccionarConjuntoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/usuarios': {
      id: '/_authenticated/super-admin/usuarios'
      path: '/usuarios'
      fullPath: '/super-admin/usuarios'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/conjuntos': {
      id: '/_authenticated/super-admin/conjuntos'
      path: '/conjuntos'
      fullPath: '/super-admin/conjuntos'
      preLoaderRoute: typeof AuthenticatedSuperAdminConjuntosRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/equipo': {
      id: '/_authenticated/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AuthenticatedAdminEquipoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/c/$complexSlug': {
      id: '/_authenticated/c/$complexSlug'
      path: '/c/$complexSlug'
      fullPath: '/c/$complexSlug'
      preLoaderRoute: typeof AuthenticatedCComplexSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$complexSlug/': {
      id: '/_authenticated/c/$complexSlug/'
      path: '/'
      fullPath: '/c/$complexSlug/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/super-admin/organizaciones/$orgId': {
      id: '/_authenticated/super-admin/organizaciones/$orgId'
      path: '/organizaciones/$orgId'
      fullPath: '/super-admin/organizaciones/$orgId'
      preLoaderRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/c/$complexSlug/usuarios': {
      id: '/_authenticated/c/$complexSlug/usuarios'
      path: '/usuarios'
      fullPath: '/c/$complexSlug/usuarios'
      preLoaderRoute: typeof AuthenticatedCComplexSlugUsuariosRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/configuracion': {
      id: '/_authenticated/c/$complexSlug/configuracion'
      path: '/configuracion'
      fullPath: '/c/$complexSlug/configuracion'
      preLoaderRoute: typeof AuthenticatedCComplexSlugConfiguracionRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/vehiculos/': {
      id: '/_authenticated/c/$complexSlug/vehiculos/'
      path: '/vehiculos'
      fullPath: '/c/$complexSlug/vehiculos/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugVehiculosIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/unidades/': {
      id: '/_authenticated/c/$complexSlug/unidades/'
      path: '/unidades'
      fullPath: '/c/$complexSlug/unidades/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugUnidadesIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/residentes/': {
      id: '/_authenticated/c/$complexSlug/residentes/'
      path: '/residentes'
      fullPath: '/c/$complexSlug/residentes/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugResidentesIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/control-acceso/': {
      id: '/_authenticated/c/$complexSlug/control-acceso/'
      path: '/control-acceso'
      fullPath: '/c/$complexSlug/control-acceso/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugControlAccesoIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
    '/_authenticated/c/$complexSlug/communications/': {
      id: '/_authenticated/c/$complexSlug/communications/'
      path: '/communications'
      fullPath: '/c/$complexSlug/communications/'
      preLoaderRoute: typeof AuthenticatedCComplexSlugCommunicationsIndexRouteImport
      parentRoute: typeof AuthenticatedCComplexSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminEquipoRoute: typeof AuthenticatedAdminEquipoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminEquipoRoute: AuthenticatedAdminEquipoRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminConjuntosRoute: typeof AuthenticatedSuperAdminConjuntosRoute
  AuthenticatedSuperAdminUsuariosRoute: typeof AuthenticatedSuperAdminUsuariosRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
  AuthenticatedSuperAdminOrganizacionesOrgIdRoute: typeof AuthenticatedSuperAdminOrganizacionesOrgIdRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminConjuntosRoute:
      AuthenticatedSuperAdminConjuntosRoute,
    AuthenticatedSuperAdminUsuariosRoute: AuthenticatedSuperAdminUsuariosRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
    AuthenticatedSuperAdminOrganizacionesOrgIdRoute:
      AuthenticatedSuperAdminOrganizacionesOrgIdRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedCComplexSlugRouteRouteChildren {
  AuthenticatedCComplexSlugConfiguracionRoute: typeof AuthenticatedCComplexSlugConfiguracionRoute
  AuthenticatedCComplexSlugUsuariosRoute: typeof AuthenticatedCComplexSlugUsuariosRoute
  AuthenticatedCComplexSlugIndexRoute: typeof AuthenticatedCComplexSlugIndexRoute
  AuthenticatedCComplexSlugCommunicationsIndexRoute: typeof AuthenticatedCComplexSlugCommunicationsIndexRoute
  AuthenticatedCComplexSlugControlAccesoIndexRoute: typeof AuthenticatedCComplexSlugControlAccesoIndexRoute
  AuthenticatedCComplexSlugResidentesIndexRoute: typeof AuthenticatedCComplexSlugResidentesIndexRoute
  AuthenticatedCComplexSlugUnidadesIndexRoute: typeof AuthenticatedCComplexSlugUnidadesIndexRoute
  AuthenticatedCComplexSlugVehiculosIndexRoute: typeof AuthenticatedCComplexSlugVehiculosIndexRoute
}

const AuthenticatedCComplexSlugRouteRouteChildren: AuthenticatedCComplexSlugRouteRouteChildren =
  {
    AuthenticatedCComplexSlugConfiguracionRoute:
      AuthenticatedCComplexSlugConfiguracionRoute,
    AuthenticatedCComplexSlugUsuariosRoute:
      AuthenticatedCComplexSlugUsuariosRoute,
    AuthenticatedCComplexSlugIndexRoute: AuthenticatedCComplexSlugIndexRoute,
    AuthenticatedCComplexSlugCommunicationsIndexRoute:
      AuthenticatedCComplexSlugCommunicationsIndexRoute,
    AuthenticatedCComplexSlugControlAccesoIndexRoute:
      AuthenticatedCComplexSlugControlAccesoIndexRoute,
    AuthenticatedCComplexSlugResidentesIndexRoute:
      AuthenticatedCComplexSlugResidentesIndexRoute,
    AuthenticatedCComplexSlugUnidadesIndexRoute:
      AuthenticatedCComplexSlugUnidadesIndexRoute,
    AuthenticatedCComplexSlugVehiculosIndexRoute:
      AuthenticatedCComplexSlugVehiculosIndexRoute,
  }

const AuthenticatedCComplexSlugRouteRouteWithChildren =
  AuthenticatedCComplexSlugRouteRoute._addFileChildren(
    AuthenticatedCComplexSlugRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedSeleccionarConjuntoRoute: typeof AuthenticatedSeleccionarConjuntoRoute
  AuthenticatedCComplexSlugRouteRoute: typeof AuthenticatedCComplexSlugRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedSeleccionarConjuntoRoute: AuthenticatedSeleccionarConjuntoRoute,
  AuthenticatedCComplexSlugRouteRoute:
    AuthenticatedCComplexSlugRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CuentaDesactivadaRoute: CuentaDesactivadaRoute,
  ErrorAuthRoute: ErrorAuthRoute,
  InvitacionExpiradaRoute: InvitacionExpiradaRoute,
  InvitacionRevocadaRoute: InvitacionRevocadaRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  NoAutorizadoRoute: NoAutorizadoRoute,
  NoRegistradoRoute: NoRegistradoRoute,
  OrganizacionInactivaRoute: OrganizacionInactivaRoute,
  ProgressRoute: ProgressRoute,
  TunnelRoute: TunnelRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
